baseurl = "https://amarildolucas.herokuapp.com/"
title = "Amarildo"
author = "Amarildo Lucas"
copyright = "© 2017 Amarildo Lucas"
canonifyurls = true
paginate = 5
googleAnalytics = ""
theme = "strange-case"
languageCode = "pt"
disqusShortname = "amarildolucas"

[params]
	DateFormat = "02/01 de 2006"
	description = "Computadores, Café e Spotify"
	sidebarDescription = ""
	sidebarFreeText = ""
	piwikSiteID = ""
	piwikURL = ""

[[menu.main]]
	name = "Twitter"
	post = "<span class='glyphicon glyphicon-twitter'></span>"
	url = "https://twitter.com/amarildojclucas"
